### ISSUE TITLE
Branding-Okay Eclipse prompts not cool

### ISSUE THREAD

**Issue by kmedidi** [snaraya7/Ok_Eclipse#3]
Use "Couldn't catch that!" when voice command not recognized.
Use "Listening... Fire away!" instead of "Speak now"
Use "Include progress bar when searching Stackoverflow" instead of "Not Responding"

**Comment by snaraya7** [comment]
Use "Couldn't catch that!" when voice command not recognized. (Accepted)
Use "Listening... Fire away!" instead of "Speak now" ( Speak now is better will explain in person)
Use "Include progress bar when searching Stackoverflow" instead of "Not Responding" (Accepted)

Done!
